# ===== Servidor =====
server.port=8080

# ===== Base de datos MySQL =====
# Antes de ejecutar, crea la base de datos:
#   CREATE DATABASE db_gimnasio;
spring.datasource.url=jdbc:mysql://localhost:3306/db_gimnasio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===== JWT =====
# Clave secreta usada para firmar los tokens (cambiarla en produccion)
jwt.secret=CibertecGimnasioSecretKeyParaFirmarTokensJWT2026SuperSegura
jwt.expiration.ms=86400000

# ===== CORS (para que Angular en localhost:4200 pueda consumir la API) =====
app.cors.allowed-origin=http://localhost:4200
